import logging
import os
from datetime import datetime as dt

from parameters import get_parameters, get_data

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# parse parameters (generated by gotap at container build time)
params = get_parameters()
data = get_data()

# check if a toolname was set in env
toolname = os.environ.get('TOOL_RUN', 'foobar').lower()

# switch the tool
if toolname == 'foobar':
    # RUN the tool here and create the output in /out
    logger.info('This toolbox does not include any tool. Did you run the template?\n')

    logger.info(vars(params))

    for name, path in data.items():
        logger.info(f"\n### {name}: %s", path)

# In any other case, it was not clear which tool to run
else:
    raise AttributeError(f"[{dt.now().isocalendar()}] Either no TOOL_RUN environment variable available, or '{toolname}' is not valid.\n")